import 'package:flutter/material.dart';
import '../../config/app_theme.dart';
import '../../localization/app_localizations.dart';
import '../../screens/settings/settings_screen.dart';
import 'player_selection_screen.dart';

class HomeScreen extends StatelessWidget { const HomeScreen({super.key, required this.onLocaleChanged, required this.onThemeChanged}); final ValueChanged<Locale> onLocaleChanged; final ValueChanged<bool> onThemeChanged;
  @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 520), child: Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Spacer(), Row(children: [Container(width: 68, height: 68, decoration: BoxDecoration(color: AppTheme.green, borderRadius: BorderRadius.circular(22)), child: const Icon(Icons.casino, color: Colors.white, size: 38)), const SizedBox(width: 16), Text('LUDO DZ', style: Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.w900, letterSpacing: 2))]), const SizedBox(height: 18), Text(context.l10n.text('tagline'), style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 36), SizedBox(width: double.infinity, child: ElevatedButton.icon(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const PlayerSelectionScreen())), icon: const Icon(Icons.play_arrow), label: Text(context.l10n.text('localGame')))), const SizedBox(height: 12), SizedBox(width: double.infinity, child: OutlinedButton.icon(onPressed: () => Navigator.push(context, MaterialPageRoute(builder: (_) => const SettingsScreen())), icon: const Icon(Icons.settings), label: Text(context.l10n.text('settings')))), const Spacer(), Center(child: Text('GREEN • WHITE • RED • GOLD', style: Theme.of(context).textTheme.labelSmall?.copyWith(letterSpacing: 2, color: AppTheme.red, fontWeight: FontWeight.bold))) ])))))); }
}
