import 'dart:math';
import 'package:flutter/material.dart';
import '../../config/app_theme.dart';
import '../../game/local_game_controller.dart';
import '../../game/ludo_rules.dart';
import '../../models/game_models.dart';
import '../../profile/profile_service.dart';

class GameScreen extends StatefulWidget { const GameScreen({super.key, required this.controller}); final LocalGameController controller; @override State<GameScreen> createState() => _GameScreenState(); }
class _GameScreenState extends State<GameScreen> with SingleTickerProviderStateMixin {
  late final AnimationController _dice = AnimationController(vsync: this, duration: const Duration(milliseconds: 420));
  String? _lastWinner;
  @override void initState() { super.initState(); widget.controller.addListener(_changed); }
  @override void dispose() { widget.controller.removeListener(_changed); widget.controller.dispose(); _dice.dispose(); super.dispose(); }
  void _changed() { if (widget.controller.state.dice != null) _dice.forward(from: 0); final winner = widget.controller.state.winnerId; if (winner != null && winner != _lastWinner) { _lastWinner = winner; ProfileService.instance.recordWin(); } if (mounted) setState(() {}); }
  @override Widget build(BuildContext context) { final game = widget.controller; final active = game.state.players[game.state.currentPlayer]; return Scaffold(appBar: AppBar(title: const Text('Ludo DZ'), actions: [IconButton(tooltip: game.paused ? 'Resume' : 'Pause', onPressed: game.togglePause, icon: Icon(game.paused ? Icons.play_arrow : Icons.pause)), IconButton(tooltip: 'Restart', onPressed: () => game.restart(), icon: const Icon(Icons.refresh))]), body: SafeArea(child: LayoutBuilder(builder: (_, c) => SingleChildScrollView(padding: const EdgeInsets.all(14), child: Column(children: [_TurnPanel(player: active, dice: game.state.dice, paused: game.paused), const SizedBox(height: 12), AspectRatio(aspectRatio: 1, child: _LudoBoard(state: game.state, legal: game.legalTokens, onToken: game.move)), const SizedBox(height: 14), ScaleTransition(scale: Tween(begin: .8, end: 1.0).animate(CurvedAnimation(parent: _dice, curve: Curves.elasticOut)), child: ElevatedButton.icon(onPressed: game.paused || game.isBotTurn || game.state.dice != null || game.state.winnerId != null ? null : game.roll, icon: const Icon(Icons.casino), label: Text(game.state.dice == null ? 'ROLL DICE' : 'SELECT A PIECE'))), if (game.state.winnerId != null) _WinnerPanel(player: active, onRematch: game.restart)])))); }
}
class _TurnPanel extends StatelessWidget { const _TurnPanel({required this.player, required this.dice, required this.paused}); final PlayerState player; final int? dice; final bool paused; @override Widget build(BuildContext context) => Card(child: ListTile(leading: CircleAvatar(backgroundColor: _color(player.color), child: Text(player.name.substring(0, 1))), title: Text(paused ? 'Game paused' : '${player.name}’s turn', style: const TextStyle(fontWeight: FontWeight.bold)), subtitle: Text(dice == null ? 'Roll the dice' : 'Select a highlighted token'), trailing: dice == null ? const Icon(Icons.hourglass_empty) : Text('$dice', style: const TextStyle(fontSize: 28, fontWeight: FontWeight.w900)))); }
class _WinnerPanel extends StatelessWidget { const _WinnerPanel({required this.player, required this.onRematch}); final PlayerState player; final VoidCallback onRematch; @override Widget build(BuildContext context) => Card(color: AppTheme.green.withOpacity(.14), child: Padding(padding: const EdgeInsets.all(18), child: Column(children: [Text('${player.name} wins! 🎉', style: Theme.of(context).textTheme.headlineSmall?.copyWith(color: AppTheme.green, fontWeight: FontWeight.w900)), const SizedBox(height: 8), OutlinedButton.icon(onPressed: onRematch, icon: const Icon(Icons.replay), label: const Text('REMATCH'))]))); }
class _LudoBoard extends StatelessWidget { const _LudoBoard({required this.state, required this.legal, required this.onToken}); final GameState state; final List<int> legal; final ValueChanged<int> onToken;
  @override Widget build(BuildContext context) => Container(decoration: BoxDecoration(color: Theme.of(context).cardColor, borderRadius: BorderRadius.circular(24), boxShadow: const [BoxShadow(color: Colors.black26, blurRadius: 16, offset: Offset(0, 7))]), padding: const EdgeInsets.all(8), child: LayoutBuilder(builder: (_, box) => Stack(children: [GridView.count(crossAxisCount: 7, physics: const NeverScrollableScrollPhysics(), children: [for (var i = 0; i < 49; i++) _trackCell(i)]), ..._homeZones(box.biggest), ..._allTokens(box.biggest)])));
  Widget _trackCell(int cell) { final safe = LudoRules.safeCells.contains(cell); return Container(margin: const EdgeInsets.all(2), decoration: BoxDecoration(color: safe ? AppTheme.gold.withOpacity(.2) : Colors.grey.withOpacity(.08), borderRadius: BorderRadius.circular(5), border: safe ? Border.all(color: AppTheme.gold, width: 1.3) : null), child: safe ? const Icon(Icons.star, size: 12, color: AppTheme.gold) : null); }
  List<Widget> _homeZones(Size s) { final size = s.shortestSide / 7 * 2.5; final places = [Offset.zero, Offset(s.width - size, 0), Offset(0, s.height - size), Offset(s.width - size, s.height - size)]; return [for (var i = 0; i < state.players.length; i++) Positioned(left: places[i].dx, top: places[i].dy, width: size, height: size, child: IgnorePointer(child: DecoratedBox(decoration: BoxDecoration(color: _color(state.players[i].color).withOpacity(.12), borderRadius: BorderRadius.circular(18), border: Border.all(color: _color(state.players[i].color).withOpacity(.35), width: 2))))]; }
  List<Widget> _allTokens(Size s) { final result = <Widget>[]; for (final player in state.players) { for (final token in state.tokens[player.id]!) { final cell = token.isHome || token.isFinished ? null : LudoRules.boardCell(player.color, token.progress); if (cell == null) continue; final col = cell % 7; final row = cell ~/ 7; result.add(Positioned(left: col * s.width / 7 + 6, top: row * s.height / 7 + 6, child: GestureDetector(onTap: player.id == state.players[state.currentPlayer].id && legal.contains(token.id) ? () => onToken(token.id) : null, child: AnimatedScale(scale: legal.contains(token.id) ? 1.15 : 1, duration: const Duration(milliseconds: 220), child: Container(width: min(28, s.width / 10), height: min(28, s.width / 10), decoration: BoxDecoration(color: _color(player.color), shape: BoxShape.circle, border: Border.all(color: Colors.white, width: legal.contains(token.id) ? 3 : 1), boxShadow: const [BoxShadow(color: Colors.black38, blurRadius: 4)]), child: Center(child: Text('${token.id + 1}', style: const TextStyle(color: Colors.white, fontSize: 9, fontWeight: FontWeight.bold))))))); } } return result; }
}
Color _color(PlayerColor c) => switch (c) { PlayerColor.red => AppTheme.red, PlayerColor.green => AppTheme.green, PlayerColor.yellow => AppTheme.gold, PlayerColor.blue => AppTheme.blue };
