import 'package:flutter/material.dart';
import '../../config/app_theme.dart';
import '../../game/local_game_controller.dart';
import '../../game/ludo_rules.dart';
import '../../models/game_models.dart';

class GameScreen extends StatefulWidget { const GameScreen({super.key, required this.controller}); final LocalGameController controller; @override State<GameScreen> createState() => _GameScreenState(); }
class _GameScreenState extends State<GameScreen> with SingleTickerProviderStateMixin { late final diceAnimation = AnimationController(vsync: this, duration: const Duration(milliseconds: 450)); @override void initState() { super.initState(); widget.controller.addListener(_refresh); } @override void dispose() { widget.controller.removeListener(_refresh); widget.controller.dispose(); diceAnimation.dispose(); super.dispose(); } void _refresh() { if (widget.controller.state.dice != null) diceAnimation.forward(from: 0); if (mounted) setState(() {}); }
  @override Widget build(BuildContext context) { final game = widget.controller; final active = game.state.players[game.state.currentPlayer]; return Scaffold(appBar: AppBar(title: const Text('Ludo DZ'), actions: [IconButton(onPressed: game.togglePause, icon: Icon(game.paused ? Icons.play_arrow : Icons.pause)), IconButton(onPressed: () => _restart(context), icon: const Icon(Icons.refresh))]), body: SafeArea(child: LayoutBuilder(builder: (_, constraints) => SingleChildScrollView(padding: const EdgeInsets.all(14), child: Column(children: [_TurnCard(player: active, dice: game.state.dice, paused: game.paused), const SizedBox(height: 12), AspectRatio(aspectRatio: 1, child: _Board(state: game.state, legal: game.legalTokens, onToken: game.move)), const SizedBox(height: 14), ScaleTransition(scale: Tween(begin: .85, end: 1.0).animate(CurvedAnimation(parent: diceAnimation, curve: Curves.elasticOut)), child: ElevatedButton.icon(onPressed: game.paused || game.isBotTurn || game.state.dice != null || game.state.winnerId != null ? null : game.roll, icon: const Icon(Icons.casino), label: Text(game.state.dice == null ? 'ROLL DICE' : 'SELECT PIECE'))), if (game.state.winnerId != null) _ResultCard(player: active, onRestart: () => _restart(context))])))); }
  Future<void> _restart(BuildContext context) async { final yes = await showDialog<bool>(context: context, builder: (_) => AlertDialog(title: const Text('Restart game?'), actions: [TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('CANCEL')), FilledButton(onPressed: () => Navigator.pop(context, true), child: const Text('RESTART'))])); if (yes == true) widget.controller.restart(); }
}
class _TurnCard extends StatelessWidget { const _TurnCard({required this.player, required this.dice, required this.paused}); final PlayerState player; final int? dice; final bool paused; @override Widget build(BuildContext context) => Card(child: ListTile(leading: CircleAvatar(backgroundColor: _color(player.color), child: Text(player.name[0])), title: Text(paused ? 'Game paused' : '${player.name}’s turn'), subtitle: Text(dice == null ? 'Roll the dice' : 'Choose a highlighted piece'), trailing: dice == null ? const Icon(Icons.hourglass_empty) : Text('$dice', style: const TextStyle(fontSize: 28, fontWeight: FontWeight.bold)))); }
class _ResultCard extends StatelessWidget { const _ResultCard({required this.player, required this.onRestart}); final PlayerState player; final VoidCallback onRestart; @override Widget build(BuildContext context) => Card(color: AppTheme.green.withOpacity(.12), child: Padding(padding: const EdgeInsets.all(18), child: Column(children: [Text('${player.name} wins! 🎉', style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w900, color: AppTheme.green)), const SizedBox(height: 10), OutlinedButton.icon(onPressed: onRestart, icon: const Icon(Icons.replay), label: const Text('REMATCH'))]))); }
class _Board extends StatelessWidget { const _Board({required this.state, required this.legal, required this.onToken}); final GameState state; final List<int> legal; final ValueChanged<int> onToken;
  @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: Theme.of(context).cardColor, borderRadius: BorderRadius.circular(24), boxShadow: const [BoxShadow(color: Colors.black26, blurRadius: 14)]), child: GridView.count(crossAxisCount: 7, physics: const NeverScrollableScrollPhysics(), children: [for (var i = 0; i < 49; i++) _cell(i)]);
  Widget _cell(int cell) { final token = _tokens(cell); final safe = LudoRules.safeCells.contains(cell); return Container(margin: const EdgeInsets.all(2), decoration: BoxDecoration(color: token == null ? (safe ? AppTheme.gold.withOpacity(.2) : Colors.grey.withOpacity(.08)) : _color(token.$1.color).withOpacity(.24), borderRadius: BorderRadius.circular(6), border: safe ? Border.all(color: AppTheme.gold) : null), child: Stack(alignment: Alignment.center, children: [if (safe) const Icon(Icons.star, size: 12, color: AppTheme.gold), if (token != null) ..._tokenWidgets(token.$1, token.$2)])); }
  (PlayerState, TokenState)? _tokens(int cell) { for (final player in state.players) { for (final token in state.tokens[player.id]!) { if (!token.isHome && !token.isFinished && LudoRules.boardCell(player.color, token.progress) == cell) return (player, token); } } return null; }
  List<Widget> _tokenWidgets(PlayerState player, TokenState token) => [GestureDetector(onTap: player.id == state.players[state.currentPlayer].id && legal.contains(token.id) ? () => onToken(token.id) : null, child: AnimatedContainer(duration: const Duration(milliseconds: 250), width: 25, height: 25, decoration: BoxDecoration(color: _color(player.color), shape: BoxShape.circle, border: Border.all(color: legal.contains(token.id) ? Colors.white : Colors.white70, width: legal.contains(token.id) ? 3 : 1)), child: Center(child: Text('${token.id + 1}', style: const TextStyle(color: Colors.white, fontSize: 9, fontWeight: FontWeight.bold)))) )];
}
Color _color(PlayerColor c) => switch (c) { PlayerColor.red => AppTheme.red, PlayerColor.green => AppTheme.green, PlayerColor.yellow => AppTheme.gold, PlayerColor.blue => AppTheme.blue };
